wget -O smh.html "http://www.smh.com.au"  
wget -O cnyahoo.html "http://cn.yahoo.com" 
wget -O bbc.html "http://www.bbc.co.uk" 
wget -O ms.html "http://www.microsoft.com" 
wget -O medj.html "http://www.medjugorje.hr/hr" 
wget -O jerusalempost.html "http://www.jpostlite.co.il" 
wget -O japantimes.html "http://club.japantimes.co.jp/jt" 
wget -O hp.html "http://welcome.hp.com/country/jp/ja/cs/home.html" 
